dateModified: 1718561202
elementSources:
  craft\elements\User:
    -
      key: '*'
      type: native
    -
      key: admins
      type: native
    -
      heading: 'Account Type'
      type: heading
    -
      key: credentialed
      type: native
    -
      key: inactive
      type: native
    -
      heading: Groups
      type: heading
    -
      defaultSort:
        - username
        - asc
      disabled: false
      key: 'group:adf21248-5e45-44f0-a3d9-b2ece6004c5e' # Contributors
      tableAttributes:
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      key: 'group:4a5cdf1b-642d-4a37-854f-c3b1168bea2d' # Editors
      type: native
    -
      key: 'group:429e38b0-5490-4b1b-be5e-99adcf0d6c47' # Sales
      type: native
    -
      defaultSort:
        - username
        - asc
      disabled: false
      key: 'group:7ef5f597-7ee8-473c-9647-ba485d262e5a' # Subscriber
      tableAttributes:
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      heading: Subscribers
      type: heading
    -
      condition:
        class: craft\elements\conditions\users\UserCondition
        conditionRules:
          -
            class: craft\elements\conditions\users\GroupConditionRule
            operator: in
            uid: eab66ea2-e6b8-4196-9824-79352af7daa0
            values:
              - 7ef5f597-7ee8-473c-9647-ba485d262e5a # Subscriber
          -
            class: craft\fields\conditions\OptionsFieldConditionRule
            fieldUid: 944c11ef-571f-4e08-a4bb-db2540e4b404 # Subscription - Plan
            operator: in
            uid: b3f09856-6988-443b-b9dc-b929e4a623aa
            values:
              - regular
        elementType: craft\elements\User
        fieldContext: global
      defaultSort:
        - dateCreated
        - desc
      key: 'custom:fc585b69-a1d7-4a9e-a3b5-42baaac9fad8'
      label: Regular
      tableAttributes:
        - email
        - 'field:944c11ef-571f-4e08-a4bb-db2540e4b404' # Subscription - Plan
        - 'field:20bb750f-abb8-42b0-9ba8-adf65d1ee624' # Legacy - End Date
        - dateCreated
      type: custom
      userGroups:
        - 4a5cdf1b-642d-4a37-854f-c3b1168bea2d # Editors
    -
      condition:
        class: craft\elements\conditions\users\UserCondition
        conditionRules:
          -
            class: craft\elements\conditions\users\GroupConditionRule
            operator: in
            uid: 4478e6b4-9672-4061-9515-124133f91735
            values:
              - 7ef5f597-7ee8-473c-9647-ba485d262e5a # Subscriber
          -
            class: craft\fields\conditions\OptionsFieldConditionRule
            fieldUid: 944c11ef-571f-4e08-a4bb-db2540e4b404 # Subscription - Plan
            operator: in
            uid: faf1ed3f-aeaf-4346-9473-dbd05b18a806
            values:
              - student
        elementType: craft\elements\User
        fieldContext: global
      defaultSort:
        - username
        - desc
      key: 'custom:c9764f5a-b696-4ee4-99d2-c4b4f44469c5'
      label: Student
      tableAttributes:
        - email
        - 'field:944c11ef-571f-4e08-a4bb-db2540e4b404' # Subscription - Plan
        - 'field:20bb750f-abb8-42b0-9ba8-adf65d1ee624' # Legacy - End Date
        - dateCreated
      type: custom
      userGroups:
        - 4a5cdf1b-642d-4a37-854f-c3b1168bea2d # Editors
    -
      condition:
        class: craft\elements\conditions\users\UserCondition
        conditionRules:
          -
            class: craft\elements\conditions\users\GroupConditionRule
            operator: in
            uid: 2c3ad3eb-0474-42e9-8484-8c75f7acc9b0
            values:
              - 7ef5f597-7ee8-473c-9647-ba485d262e5a # Subscriber
          -
            class: craft\fields\conditions\DateFieldConditionRule
            endDate: null
            fieldUid: 20bb750f-abb8-42b0-9ba8-adf65d1ee624 # Legacy - End Date
            periodType: minutesFromNow
            periodValue: 1.0
            rangeType: after
            startDate: null
            uid: ef962cc3-4481-4e71-8010-9e4a163c12c9
        elementType: craft\elements\User
        fieldContext: global
      defaultSort:
        - username
        - desc
      key: 'custom:688a1a87-de6f-4342-ab33-110ed85e1d7f'
      label: Active
      tableAttributes:
        - email
        - 'field:944c11ef-571f-4e08-a4bb-db2540e4b404' # Subscription - Plan
        - 'field:20bb750f-abb8-42b0-9ba8-adf65d1ee624' # Legacy - End Date
        - dateCreated
      type: custom
      userGroups:
        - 4a5cdf1b-642d-4a37-854f-c3b1168bea2d # Editors
email:
  fromEmail: redaktion@zsonline.ch
  fromName: 'Zürcher Studierendenzeitung'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  embeds:
    hasUrls: false
    name: Embeds
    settings:
      path: '@storage/assets/embeds'
    type: craft\fs\Local
    url: null
  public:
    hasUrls: true
    name: Public
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0cf2962b-f593-4e6b-9ac2-9544710d8aad: 'Home Section Layout - Appearance' # Home Section Layout - Appearance
    1bf3a5c8-628e-4b3c-b18b-aa384eec608e: 'Article - Format' # Article - Format
    1ee4a9c1-5b55-4094-bd47-fb1c7c2ec826: 'Legacy - Description' # Legacy - Description
    2ef3f3d8-ae1c-480e-a51b-db580170d832: Formats # Formats
    3a27561f-43cc-469a-a2fa-6920676a2b3a: 'Timeline - Description' # Timeline - Description
    3cc8b7a7-5c00-4889-b691-ca2edc74df61: Ad # Ad
    4a5cdf1b-642d-4a37-854f-c3b1168bea2d: Editors # Editors
    4ce497c4-83db-4505-966c-25ac2477e7fb: Ads # Ads
    4d2d5d09-2278-47d1-8e63-1b70ad5116b4: 'Content Gallery - Images' # Content Gallery - Images
    4e85c514-8a85-45c7-996a-0824ef8d667b: 'Timeline - Description' # Timeline - Description
    5a09781f-aab3-4633-b3ed-6bd0bda1ad48: 'Legacy - Content' # Legacy - Content
    5bbeef56-cf6d-449b-9e83-18322e58ec53: 'Content File' # Content File
    5c6da112-a718-4124-97fb-97f8c5b0ac06: 'Content Image' # Content Image
    5e969c43-23fb-4bfc-a51a-e8e26b1b66ba: 'Content File - File' # Content File - File
    5fa65803-cc01-4718-967f-17c1fac740ab: Files # Files
    6aab4182-8fbc-4f80-b6e3-504f5f487ecc: 'Article - Image' # Article - Image
    6aee99fe-72b2-4d7d-a791-a8b6b15b3118: 'Timeline Event (Article) - Image' # Timeline Event (Article) - Image
    6c7e7503-494c-4a2c-84c8-fbfb56dcbe67: 'Timeline Event - Image' # Timeline Event - Image
    6c54d505-9d57-4707-9916-cdac49a0c034: 'Content Note - Content' # Content Note - Content
    6cdd6eb7-76e7-4ae1-949a-513b1ede029c: 'Issue - Number' # Issue - Number
    7dac239d-784f-4ec9-80fc-46b2c4362060: Articles # Articles
    7ef5f597-7ee8-473c-9647-ba485d262e5a: Subscriber # Subscriber
    8b097a87-a2ec-4270-8431-a0e733b3fdb3: 'Issue - Sections' # Issue - Sections
    8bf7e76a-4365-4da0-a4c8-a545c79488c3: 'Timeline Event - Label' # Timeline Event - Label
    8c68bef4-fce4-4168-aa13-3ca1947567fb: 'Legacy - Title' # Legacy - Title
    8fc13160-607f-43ed-9ae7-e5b572317317: 'Timeline Event (Article) - Content' # Timeline Event (Article) - Content
    9a7641a1-9aa0-423c-a776-c0422cf7f378: 'Page - Image' # Page - Image
    9c4c8063-ca7a-411d-ab4e-cb9498df24c8: 'Timeline Event - Description' # Timeline Event - Description
    9d246c2e-f6f4-4ecb-a3f6-ffbb386cd5ed: 'Article - Ad' # Article - Ad
    9d3883d3-f157-4a96-a03e-5b86dbac381d: 'Timeline Event - Print Link' # Timeline Event - Print Link
    9f01ed5b-f89c-478b-a859-71fd331c8d93: 'Legacy - Title' # Legacy - Title
    09f3e7d3-dd38-4d06-ac5c-fbff3a017d92: Issues # Issues
    13c1314c-8e18-452c-99b9-40ddcf9ba5f2: 'Timeline Event - Year' # Timeline Event - Year
    15dca033-1e00-43b6-bcd3-05ca3c07b14f: 'Timeline - Image' # Timeline - Image
    18ae8f32-e01d-480d-b9b7-9b166fcdceda: Home # Home
    20bb750f-abb8-42b0-9ba8-adf65d1ee624: 'Legacy - End Date' # Legacy - End Date
    21e4a371-781d-4752-b0cd-106498851db5: 'Content Image - Image' # Content Image - Image
    024d03f4-9614-497a-9274-7340a22f343c: 'Home Section - Color' # Home Section - Color
    28f5783a-9790-439d-b079-1bc2b0cc58f9: 'Article - Related' # Article - Related
    30ad3ecb-e175-42bd-8a93-6b5432ae932f: 'Content Note - Content' # Content Note - Content
    33d4c786-8ab6-42cf-9aaa-e48f7d18b820: 'Home - Sections' # Home - Sections
    36ea09ec-8867-4d74-96ee-d55c21e44104: 'Contribution (External)' # Contribution (External)
    49b8a091-c188-4f35-a61b-6162eb8514a9: 'Image - Contributions' # Image - Contributions
    50b7bb6c-00c3-462d-8d00-1ae343ce044a: 'Article - Content' # Article - Content
    67a0dda7-852f-4f0d-ae27-228660fce59e: 'Content Note - Title' # Content Note - Title
    74e21a53-79cd-4aa7-85b3-bff442e02c68: 'Timeline Event' # Timeline Event
    91d8d1f4-db2b-49ba-9de0-187a49dd5276: 'Timeline Event (Article) - Description' # Timeline Event (Article) - Description
    92be950a-0880-49a1-bd9a-dcfdb0745a8a: 'Contribution (External) - Type' # Contribution (External) - Type
    232f0e97-046b-417c-bb0b-d38f41748a3a: 'Content Note' # Content Note
    241d2e87-c08f-4847-90e8-4ad1d718f876: Format # Format
    274b5d00-df3a-4b76-861b-ca591e2af249: 'Contribution - User' # Contribution - User
    408c6114-fd69-445a-8240-e8841521181d: 'Subscription - Address' # Subscription - Address
    420d0b54-9f18-41a9-b095-de7adfde688d: 'Ad - Image' # Ad - Image
    429e38b0-5490-4b1b-be5e-99adcf0d6c47: Sales # Sales
    438d977b-985e-4c1f-9051-8e8e9b279e22: 'Article - Topics' # Article - Topics
    614a8287-bcf0-40de-8795-3ab58a7a4d50: 'Content Quote' # Content Quote
    683c8764-91e2-4a9e-b0cf-d7bed17d1d5d: 'Timeline Event (Article)' # Timeline Event (Article)
    683cb842-2907-43f6-a6be-a4a3833c5eb5: 'Timeline Event (Article) - Year' # Timeline Event (Article) - Year
    785ebd4b-4b47-46f7-a0a2-cd889b31058e: Topic # Topic
    905c3d5a-8d0f-4831-9fbb-6f72a050f60b: 'Page - Content' # Page - Content
    944c11ef-571f-4e08-a4bb-db2540e4b404: 'Subscription - Plan' # Subscription - Plan
    950c0af3-396d-40b2-a1ca-bd4f80e037b6: 'Timeline - Events' # Timeline - Events
    3458cf19-d496-4a9e-808d-47e0b2323224: 'Home Section - Layouts' # Home Section - Layouts
    4225bf4b-ab10-4bf8-8408-2c2280a0a599: Subscription # Subscription
    4866b939-c650-45b9-97eb-3fa0eeecea01: 'Page - Content' # Page - Content
    9549d5ad-d6e4-45a6-8376-edfc95d27e18: Embeds # Embeds
    9695de25-bf17-41a7-b295-68ad5cccc6c8: Pages # Pages
    10492ed9-cbb8-423a-951b-8e0dd55b11f4: 'Home Section Layout' # Home Section Layout
    14624af3-66ba-4513-af18-0cf411fbaf74: Issue # Issue
    78967f52-4d7b-4aec-9fba-53d6aa2f5a2e: Navigation # Navigation
    732552e1-9a9c-4c59-b08a-f0b293aaf7d1: Topics # Topics
    2604525a-d068-477f-9621-13db45b69206: Article # Article
    37773290-a8f4-4562-bc4f-fb8c41a63584: 'Contribution (External) - Contributor' # Contribution (External) - Contributor
    48772033-da04-47e7-ad3b-4d3905ac7a65: Images # Images
    a3b06153-7a2e-425b-a7f7-61e925da17b9: Contribution # Contribution
    a5f90846-e207-4034-ac8f-ae2a1d0f9186: 'Timeline Event - Print Image' # Timeline Event - Print Image
    a34a04ef-5b2f-4d2a-bd51-83afb13d4337: 'Content Quote - Caption' # Content Quote - Caption
    a46d69bc-dad9-44b6-9ca0-9ce75f501b7b: 'Contribution - Type' # Contribution - Type
    a71cf75d-44bb-4489-ad90-93f218828cd1: 'Article - Lead' # Article - Lead
    a91ae399-006d-491c-be06-43159f3523fd: 'Content Quote - Quote' # Content Quote - Quote
    ab58e9ac-d8c0-428f-a72a-2132a4976859: Home # Home
    adf21248-5e45-44f0-a3d9-b2ece6004c5e: Contributors # Contributors
    ae3e2976-5a2f-441c-a712-71c849fe2a40: 'Issue Section - Articles' # Issue Section - Articles
    b0b838c9-5d25-43de-886a-bdf38b92df07: 'Article - Image Position' # Article - Image Position
    b2c997ba-ecc0-418e-86a8-20c5afd7e1d6: Page # Page
    b4fa2985-51d4-428c-a10e-130fd6687f7b: 'Timeline Event (Article) - Content' # Timeline Event (Article) - Content
    b231772f-f289-459a-98aa-4307862a26f1: 'Timeline Event (Article) - Publication' # Timeline Event (Article) - Publication
    b2237231-890f-4253-ab7f-251f41d3598c: 'Issue Section' # Issue Section
    b6909423-4a75-4b31-8af2-4ec0935f6bcb: 'Legacy - Title' # Legacy - Title
    b7794701-7ea0-40bb-8bba-27df38f94295: 'Subscription - Email' # Subscription - Email
    bcb6d13b-de66-4331-8d15-bb23ef7a9736: 'Ad - Link' # Ad - Link
    bd3e37bc-785f-4f35-a3ba-42a801ec0e80: Timeline # Timeline
    c7ddc58d-ce45-4fdd-a7b2-d1318ae1afb1: 'Timeline Event - Description' # Timeline Event - Description
    c529f035-1e02-4af8-a7f0-afe4e24e634c: 'Timeline Event (Article) - Byline' # Timeline Event (Article) - Byline
    c6375497-b7f2-4761-b74b-96fd072a5a6f: Subscriptions # Subscriptions
    cb91d72b-d6d9-439e-8e7b-f3f871694967: 'Article - Contributions' # Article - Contributions
    cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: 'Zürcher Studierendenzeitung' # Zürcher Studierendenzeitung
    d0ba75f4-0ec9-406b-8e28-5a50980147cc: 'Home Section' # Home Section
    d3dc65f7-7b0a-4ff2-b2e9-54c9ff11d3de: 'Article - Content' # Article - Content
    d5eceb6a-47a0-4c63-aff2-48afcdcf05bc: 'Article - Image Size' # Article - Image Size
    d29e8b36-a8aa-4b2f-9033-2c5e9113427c: 'Zürcher Studierendenzeitung' # Zürcher Studierendenzeitung
    d64265d4-5a86-41a5-a68e-c73f8c90123e: Timeline # Timeline
    d6607152-35ab-435a-9c88-53f1e9ab6f5c: 'Home Section - Title' # Home Section - Title
    deee59e0-88c5-4df0-b499-639671b936b2: 'Content Gallery' # Content Gallery
    e60b1147-c0d1-4999-99e3-8bbc556e4fa5: Ads # Ads
    e173ad9a-9850-43b4-a574-1029011919ef: 'Issue - File' # Issue - File
    ef819456-45fb-4c34-a4e6-e32ab105c6a3: 'Image - Caption' # Image - Caption
    f2f5a7ef-3fd4-4df1-bbd6-d2969e85c127: 'Timeline Event (Article) - Label' # Timeline Event (Article) - Label
    f4cde807-f639-4b1d-bebe-8aa3cd4de160: 'Issue - Year' # Issue - Year
    f197e112-2648-4604-852c-cf4171abc6c2: 'Home Section Layout - Articles' # Home Section Layout - Articles
    f854dd38-7b4e-4c96-94ae-741cf4593a1e: 'Content Image - Size' # Content Image - Size
    ff39e44a-c59b-40f1-9eae-5080bf251c2d: 'Issue - Cover' # Issue - Cover
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  comments:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_COMMENTS_LICENSE
    schemaVersion: 1.2.0
    settings:
      allowFlagging: false
      allowGuest: true
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: false
      autoCloseDays: null
      closed: false
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: null
      guestRequireEmailName: true
      guestShowEmailName: true
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: '2'
      maxUserComments: null
      moderatorUserGroup: 4a5cdf1b-642d-4a37-854f-c3b1168bea2d # Editors
      notificationAdminEnabled: false
      notificationAuthorEnabled: false
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: false
      notificationSubscribeEnabled: false
      outputDefaultCss: true
      outputDefaultJs: true
      permissions:
        __assoc__:
          -
            - craft\elements\Asset
            - ''
          -
            - craft\elements\Category
            - ''
          -
            - craft\elements\Entry
            -
              - 7dac239d-784f-4ec9-80fc-46b2c4362060 # Articles
          -
            - craft\elements\User
            - ''
      placeholderAvatar: null
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      requireModeration: true
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: '500'
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      sortDefaultDirection: asc
      sortDefaultKey: structure
      structureUid: f486528b-59df-4701-b1fe-60e57aba4126
      templateEmail: null
      templateFolderOverride: null
      useQueueForNotifications: true
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cacheDuration: 300
      disableVimeoTracking: false
      embedlyKey: ''
      enableAutoRefresh: true
      facebookKey: ''
      googleKey: ''
      iframelyKey: ''
      maxAssetNameLength: 50
      maxFileNameLength: 50
      minImageSize: 16
      parameters:
        -
          __assoc__:
            -
              - param
              - maxwidth
            -
              - value
              - '650'
        -
          __assoc__:
            -
              - param
              - maxheight
            -
              - value
              - '650'
      preventNonWhitelistedUploads: false
      referer: ''
      showThumbnailsInCp: true
      soundcloudKey: ''
      useYouTubeNoCookie: false
      whitelist:
        - 'amazon.*'
        - 'amazon.co.*'
        - amcharts.com
        - baidu.com
        - collegehumor.com
        - dailymotion.com
        - deviantart.com
        - embed.ly
        - 'facebook.*'
        - 'facebook.co.*'
        - 'facebook.com.*'
        - fb.com
        - 'google.*'
        - 'google.co.*'
        - 'google.com.*'
        - hulu.com
        - iframely.com
        - imgur.com
        - instagr.am
        - instagram.com
        - kickstarter.com
        - meetup.com
        - meetupstatic.com
        - netflix.com
        - pbs.org
        - nhpbs.org
        - reddit.com
        - soundcloud.com
        - tiktok.com
        - t.co
        - 'twitter.*'
        - 'twitter.co.*'
        - 'twitter.com.*'
        - twimg.com
        - vimeo.com
        - vine.co
        - wikipedia.org
        - wikimedia.org
        - wordpress.com
        - yahoo.com
        - youtu.be
        - youtube.com
        - youtube-nocookie.com
  navigation:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_NAVIGATION_LICENSE
    schemaVersion: 2.1.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Zürcher Studierendenzeitung'
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: Europe/Zurich
