defaultPlacement: end
enableVersioning: true
handle: topics
name: Topics
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cf08c3cd-b41b-4dc3-b956-6c8bf65219b4: # ZÃ¼rcher Studierendenzeitung
    enabledByDefault: true
    hasUrls: true
    template: _pages/topic.twig
    uriFormat: 'themen/{slug}'
type: channel
