name: zs
type: craftcms
docroot: web
php_version: "8.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
additional_hostnames:
  - "www.zs"
database:
  type: mariadb
  version: "10.6"
composer_version: "2"
nodejs_version: "18"
upload_dirs:
  - "assets"
  - "../storage/assets"
